spring:
   datasource:
      url: jdbc:mysql://localhost:3306/toy_store
      username: root
      password: root
   jpa:
      hibernate:
         ddl-auto: update
         database-platform: org.hibernate.dialect.MySQLInnoDBDialect
         database: mysql
